### ISSUE TITLE
getpeerinfo函数返回值不正确

### ISSUE THREAD

**Issue by wyh136** [mvs-live/metaverse#1]
返回的是空值.另外像这种公用函数有必要通过账号和密码认证吗？

**Comment by betachen** [comment]
谢谢你的建议。
所有命令是工具生成的，仅仅在实现部分会有区别，getpeerinfo命令还没有完整实现，所以会包含帐号和密码，后续我们会移除。

[参考api call list](https://github.com/mvs-live/metaverse/wiki/Metaverse-API-Call-List)

**Comment by wyh136** [comment]
那就是说我的这个建议被采纳了对吧
