### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by aparesse** [mvs-live/metaverse#30]
[100%] Linking CXX executable ../../bin/mvsd
cd /Users/impressiver/Projects/impressiver/Aparesse/metaverse/build/src/mvsd && /usr/local/Cellar/cmake/3.8.0/bin/cmake -E cmake_link_script CMakeFiles/mvsd.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -Wno-reorder -Wno-ignored-qualifiers -Wno-inconsistent-missing-override -Wno-missing-braces -Wno-mismatched-tags -Wno-overloaded-virtual -Wno-sometimes-uninitialized -Wno-macro-redefined -Wno-uninitialized -Wno-unused-private-field -Wno-unused-function -std=c++14 -Wno-braced-scalar-init -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  -stdlib=libc++ CMakeFiles/mvsd.dir/executor.cpp.o CMakeFiles/mvsd.dir/main.cpp.o CMakeFiles/mvsd.dir/mgbubble/Mongoose.cpp.o CMakeFiles/mvsd.dir/mgbubble/RestServ.cpp.o CMakeFiles/mvsd.dir/mgbubble/exception/Error.cpp.o CMakeFiles/mvsd.dir/mgbubble/exception/Exception.cpp.o CMakeFiles/mvsd.dir/mgbubble/exception/Instances.cpp.o CMakeFiles/mvsd.dir/mgbubble/utility/Stream.cpp.o CMakeFiles/mvsd.dir/mgbubble/utility/Stream_buf.cpp.o CMakeFiles/mvsd.dir/server/address_key.cpp.o CMakeFiles/mvsd.dir/server/configuration.cpp.o CMakeFiles/mvsd.dir/server/interface/address.cpp.o CMakeFiles/mvsd.dir/server/interface/blockchain.cpp.o CMakeFiles/mvsd.dir/server/interface/protocol.cpp.o CMakeFiles/mvsd.dir/server/interface/transaction_pool.cpp.o CMakeFiles/mvsd.dir/server/messages/message.cpp.o CMakeFiles/mvsd.dir/server/messages/route.cpp.o CMakeFiles/mvsd.dir/server/parser.cpp.o CMakeFiles/mvsd.dir/server/server_node.cpp.o CMakeFiles/mvsd.dir/server/services/block_service.cpp.o CMakeFiles/mvsd.dir/server/services/heartbeat_service.cpp.o CMakeFiles/mvsd.dir/server/services/query_service.cpp.o CMakeFiles/mvsd.dir/server/services/transaction_service.cpp.o CMakeFiles/mvsd.dir/server/settings.cpp.o CMakeFiles/mvsd.dir/server/utility/authenticator.cpp.o CMakeFiles/mvsd.dir/server/utility/fetch_helpers.cpp.o CMakeFiles/mvsd.dir/server/workers/notification_worker.cpp.o CMakeFiles/mvsd.dir/server/workers/query_worker.cpp.o  -o ../../bin/mvsd /usr/local/lib/libboost_date_time-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_program_options-mt.a /usr/local/lib/libboost_regex-mt.a /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_chrono-mt.a /usr/local/lib/libboost_atomic-mt.a ../../lib/libmvs_network.a ../../lib/libmvs_database.a ../../lib/libmvs_consensus.a ../../lib/libmvs_blockchain.a ../../lib/libmvs_bitcoin.a ../../lib/libmongoose.a ../../lib/libmvs_node.a ../../lib/libmvs_protocol.a ../../lib/libmvs_client.a ../../lib/libmvs_explorer.a ../../lib/libmvs_network.a ../../lib/libmvs_blockchain.a ../../lib/libmvs_database.a ../../lib/libmvs_consensus.a ../../lib/libethash.a ../../lib/libmvs_client.a ../../lib/libmvs_protocol.a ../../lib/libmvs_bitcoin.a /usr/local/lib/libboost_date_time-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_program_options-mt.a /usr/local/lib/libboost_regex-mt.a /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_chrono-mt.a /usr/local/lib/libboost_atomic-mt.a /usr/local/lib/libsecp256k1.a ../../lib/libmvs_bitcoinmath.a /usr/local/lib/libzmq.a
Undefined symbols for architecture x86_64:
  "___gmpn_gcdext", referenced from:
      _secp256k1_num_mod_inverse in libsecp256k1.a(libsecp256k1_la-secp256k1.o)
  "___gmpn_get_str", referenced from:
      _secp256k1_num_get_bin in libsecp256k1.a(libsecp256k1_la-secp256k1.o)
  "___gmpn_set_str", referenced from:
      _secp256k1_ecdsa_recover in libsecp256k1.a(libsecp256k1_la-secp256k1.o)
      _secp256k1_scalar_inverse_var in libsecp256k1.a(libsecp256k1_la-secp256k1.o)
  "___gmpn_sub_n", referenced from:
      _secp256k1_num_mod_inverse in libsecp256k1.a(libsecp256k1_la-secp256k1.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/mvsd] Error 1
make[1]: *** [src/mvsd/CMakeFiles/mvsd.dir/all] Error 2
make: *** [all] Error 2

Mac osx
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

please tell me how to solve this problem thanks

**Comment by aparesse** [comment]
I deployed hardcode to compile it successfully, add "-lgmp" in CXX_FLAGS, but also show me many warnings in the end

**Comment by betachen** [comment]
build secp256k1 in incorrect way,
please re-build as :
./configure --enable-module-recovery
